### ISSUE TITLE
Linting options

### ISSUE THREAD

**Issue by oleksbard** [fdecampredon/brackets-epic-linter#2]
Hi! It would be really helpful if plugin will have an ability to change linting preferences. Ideally it should be some GUI to do it without changing config files.

**Comment by fdecampredon** [comment]
I don't really understand what you want, could you be more descriptive please ?

**Comment by oleksbard** [comment]
I'm talking about linting preferences: 
- use function form of `use strict`
- `something` used before it was defined
- missing space between `something` and `something`
- etc

Right now Epic Linter shows nice underline and tooltip on errors:
![example](http://content.screencast.com/users/dnbard/folders/Jing/media/7336b7b7-5ca0-4764-8463-1e8e7d698ea4/2014-06-23_1058.png)

But plugin would be more useful if it would have interface or menu where linting preferences could be customized via GUI. I assume that plugin are working similar to JSHint and reads .jshintrc file (through it didn't work for me).

Or there is already an ability to customize such preferences and I'm missing it completely?

**Comment by fdecampredon** [comment]
This plugin use linter provided by brackets or his extension, it will reports exact same error that would be reported in the problems panel if you would save the file. If you have installed the JSHint extensions, you configure the preferences trough this extension, if you have installed a coffee linter you configure preferences trough this linter also. 
Basically this module only do one thing, take the errors from the linter associated to the edited file, and report them by marking those errors, and by adding a tick mark on the scrollbar. If you have problems with JSHint you should address your issue to the JSHint extension that you have installed.
