### ISSUE TITLE
EpicLinter doesn't work with splitview

### ISSUE THREAD

**Issue by JeffryBooher** [fdecampredon/brackets-epic-linter#4]
I looked at this extension and found that there may be some issues running the extension with the SplitView branch.

A more detailed explanation of what breaks and why it breaks is in the Brackets 
Extension Splitview Migration Guide. https://github.com/adobe/brackets/wiki/SplitView-Extension-Migration-Guide#extensions-that-will-break

it looks like you're computing the width for the tip based on the width of `#editor-holder` which isn't correct anymore.  Your extension still works but is probably not functioning correctly.

you can test with the branch "jeff/splitview-factory". Let us know if you need more info.

**Comment by fdecampredon** [comment]
Thanks a lot for the warning I'll try to fix it against your branch
