### ISSUE TITLE
.jshintrc file conflict

### ISSUE THREAD

**Issue by RyanJWilliams** [fdecampredon/brackets-epic-linter#6]
I've been trying out this extension and noticed that it conflicts with `.jshintrc` files used by the JSHint plugin here: https://github.com/cfjedimaster/brackets-jshint

I'm guessing this somehow occurs because Epic Linter has its own `.jshintrc` that I assume overrides any others. A specific example of this being problematic is when one wishes to see warnings when `console` is used, because the Epic Linter `.jshintrc` always sets it as a permitted global

Perhaps it'd be good to look into using JSHint's design of recursive overriding, i.e. a `.jshintrc` in a directory will affect anything below that directory but `.jshintrc` files in child directories can override, ad infinitum.

Concretely, I would expect a `.jshintrc` file anywhere in my project structure to work as intended.

**Comment by fdecampredon** [comment]
I don't really understand the issue here,
Just a memor epic-linter just consume errors reported by the brackets linters so it does not try to look for .jshintrc nor to lint the code itself it just add error mark and tick.
Could you describe your problem knowing that ?

**Comment by RyanJWilliams** [comment]
The problem is that Epic Linter itself has a `.jshintrc` file here:

https://github.com/fdecampredon/brackets-epic-linter/blob/master/.jshintrc

When Brackets is set up to use JSHint (by default it uses JSLint), the Epic Linter `.jshintrc` file overrides users' settings in their own `.jshintrc` files.

**Comment by fdecampredon** [comment]
How is it possible ? it's just a .jshintrc used for the project itself and not read nor bundled with the extension (if you look at the makefile that create the zip you'll see that it's not)

**Comment by RyanJWilliams** [comment]
I'm unsure, I'll have to take a closer look when I get home tonight. I've just tried to reproduce on my Windows machine and it isn't happening now, however it was definitely happening at home on OS X the other day. I'll try and reduce my OS X installation of Brackets to just Epic Linter and JSHint and see if it still occurs.

**Comment by RyanJWilliams** [comment]
OK, too another look at this on OS X and the issue I was getting before has mysteriously resolved itself. I must have been getting some weird temporary glitch due to adding/removing a few extensions in succession.

**Comment by fdecampredon** [comment]
ok :) I close it so
